/**
 * Schema model root owns the logical schema contract: DSL entrypoints, schema/query types,
 * timestamps, and DDL helpers. DSL-token detail, planning hooks, normalization, mapping,
 * definition, enum-link resolution, and validation live behind explicit subpaths.
 */
export { asIso8601Timestamp, type Iso8601TimestampString, type TimestampValue } from "./timestamps";
export type {
  AggregateFunction,
  CheckConstraint,
  ColumnDefinition,
  ColumnValue,
  FilterClauseBase,
  ForeignKeyConstraint,
  NullFilterClause,
  PhysicalDialect,
  PrimaryKeyConstraint,
  QueryRow,
  ReferentialAction,
  ScalarFilterClause,
  ScanFilterClause,
  ScanFilterOperator,
  ScanOrderBy,
  SchemaBuilder,
  SchemaDataEntityHandle,
  SchemaDefinition,
  SchemaValueCoercion,
  SchemaValueCoercionName,
  SqlScalarType,
  SqlTypeValue,
  TableAggregateMetric,
  TableAggregateRequest,
  TableColumnDefinition,
  TableColumns,
  TableConstraints,
  TableDefinition,
  TableLookupRequest,
  TableMethods,
  TableMethodsForSchema,
  TableMethodsMap,
  TableRow,
  TableScanRequest,
  UniqueConstraint,
} from "./types";
export { createSchemaBuilder, defineTableMethods, isSchemaBuilder } from "./dsl/builder";
export { toSqlDDL, type SqlDdlOptions } from "./ddl";
